jobs:
  workflow:
    name: Ci
    runs-on: ubuntu-20.04

    steps:
      - name: Startup
        uses: actions/checkout@v2
      - name: Download Libraries
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Test
        run: ./action/verify

name: Check

on:
  schedule:
    - cron: "15 */6 * * *"
